#!/usr/bin/env node

var http = require("http");
var express = require('express');
var app = express();
var bodyParser = require('body-parser');
var redis = require('redis');

var client = redis.createClient();
client.on('connect', function() {
});

app.use(bodyParser.urlencoded({
    extended: true
}));

app.use(bodyParser.json());

var arguments = process.argv.slice(2);
var command = arguments[0];
var word = arguments[1];
console.log(command, word);


client.hgetall(word, function(err, reply) {
  if(reply == null || reply[command] == undefined) {
    var name = word;
    client.hmset(word, {
      name: name
    },  function(err, reply) {
    });
    callApi('word.json', word, command);
  } else {
    console.log(reply[command]);
  }
});

function callApi(apiType, word, choice ) {

  var result = {};
  var param = '';
  if (choice === 'def') {
    choice = 'definitions';
  } else if (choice === 'ant' || choice == 'syn') {
    param = 'relationshipTypes='+choice+'onym&';
    choice = 'relatedWords';
  } else if (choice === 'ex') {
    choice = 'examples';
  }

  var options = {
    host: 'api.wordnik.com',
    path: '/v4/'+apiType+'/'+word+'/'+choice+'?'+param+'api_key=a2a73e7b926c924fad7001ca3111acd55af2ffabf50eb4ae5'
  };


  callback = function (response) {

    var str = '';

    response.on('data', function(chunk) {
      str += chunk;
    })

    response.on('end', function() {
      result = JSON.parse(str);
      client.hgetall(word, function(err, wordObj) {
        if(choice == 'relatedWords') {
          var onym = param.substr(18,3);
          var res = "";
          console.log("\nThe "+param.substr(18,3)+'onyms are: \n');
          for( var i = 0 ; i < result[0].words.length; i++ ) {
            res = res + "\n" + (i+1)+". "+result[0].words[i]+"\n";
          }
          wordObj[onym] = res;
          client.hmset(word, wordObj, function(err, reply) {
            console.log(res);
          });
        } else if( choice == 'definitions') {
          var def = "";
          console.log("\nThe definitions are: \n");
          for( var i = 0 ; i < result.length; i++ ) {
            def = def + "\n"+(i+1)+". "+result[i].text+"\n";
          }
          wordObj.def = def;
          client.hmset(word, wordObj, function(err, reply) {
            console.log(def);
          });
        } else if(choice = 'examples' ) {
          var ex = "";
          console.log("\nThe examples are: \n");
          for( var i = 0 ; i < result.examples.length; i++ ) {
            ex = ex+ "\n"+(i+1)+". "+result.examples[i].text+"\n";
          }
          wordObj.ex = ex;
          client.hmset(word, wordObj, function(err, reply) {
            console.log(ex);
          });
        }

      }) // end redis get

    }); // end response.end

  } // end callback

  var req = http.request(options, callback).end();
} // end callApi