#!/usr/bin/env node

var http = require("http");
var express = require('express');
var app = express();
var bodyParser = require('body-parser');
var redis = require('redis');

var client = redis.createClient();
client.on('connect', function() {
});

app.use(bodyParser.urlencoded({
    extended: true
}));

app.use(bodyParser.json());

var arguments = process.argv.slice(2);
var command = "";
var word = "";

function perform(command) {
  if(command === "dict") {
    perform("def");
    perform("syn");
    perform("ant");
    perform("ex");
    return;
  }
  var choice="", msg="", param="";
  if (command === 'def') {
    choice = 'definitions';
    msg = choice;
  } else if (command === 'ant' || command == 'syn') {
    param = 'relationshipTypes='+command+'onym&';
    msg = command+"onyms";
    choice = 'relatedWords';
  } else if (command === 'ex') {
    choice = 'examples';
    msg = choice;
  }
  client.hgetall(word, function(err, reply) {
    if(reply == null || reply[command] == undefined) {
      var name = word;
      client.hmset(word, {
        name: name
      },  function(err, reply) {
      });
      callApi('word.json', word, choice, param);
    } else {
      console.log(("\n\nThe "+msg+" are:").toUpperCase());
      console.log(reply[command]);
    }
  });  
}

if(arguments.length === 1 || command === "dict") {
  word = arguments[0];
  perform("dict");
} else if(arguments.length === 0) {

} else {
  command = arguments[0];
  word = arguments[1];
  perform(command);
}

function callApi(apiType, word, choice, param) {

  var result = {};

  var options = {
    host: 'api.wordnik.com',
    path: '/v4/'+apiType+'/'+word+'/'+choice+'?'+param+'api_key=a2a73e7b926c924fad7001ca3111acd55af2ffabf50eb4ae5'
  };


  callback = function (response) {

    var str = '';

    response.on('data', function(chunk) {
      str += chunk;
    })

    response.on('end', function() {
      result = JSON.parse(str);
      client.hgetall(word, function(err, wordObj) {
        if(choice === 'relatedWords' && result[0] ) {
          var onym = param.substr(18,3);
          var res = "";
          for( var i = 0 ; i < result[0].words.length; i++ ) {
            res = res + "\n" + (i+1)+". "+result[0].words[i]+"\n";
          }
          wordObj[onym] = res;
          client.hmset(word, wordObj, function(err, reply) {
            console.log(("\nThe "+param.substr(18,3)+'onyms are: \n').toUpperCase());
            console.log(res);
          });
        } else if( choice === 'definitions' && result) {
          var def = "";
          for( var i = 0 ; i < result.length; i++ ) {
            def = def + "\n"+(i+1)+". "+result[i].text+"\n";
          }
          wordObj.def = def;
          client.hmset(word, wordObj, function(err, reply) {
            console.log(("\nThe definitions are: \n").toUpperCase());
            console.log(def);
          });
        } else if(choice === 'examples' && result.examples) {
          var ex = "";
          for( var i = 0 ; i < result.examples.length; i++ ) {
            ex = ex+ "\n"+(i+1)+". "+result.examples[i].text+"\n";
          }
          wordObj.ex = ex;
          client.hmset(word, wordObj, function(err, reply) {
            console.log(("\nThe examples are: \n").toUpperCase());
            console.log(ex);
          });
        }

      }) // end redis get

    }); // end response.end

  } // end callback

  var req = http.request(options, callback).end();
} // end callApi